# Generated by Django 2.2.2 on 2020-06-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='site_access',
            field=models.ManyToManyField(blank=True, related_name='site_access', to='members.Site'),
        ),
    ]
