# Generated by Django 2.2.2 on 2020-06-15 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('location', models.CharField(blank=True, max_length=128)),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('color', models.CharField(max_length=32)),
                ('notes', models.CharField(blank=True, max_length=2048)),
                ('attendance_lists', models.ManyToManyField(blank=True, to='members.FilterSet')),
                ('attendees', models.ManyToManyField(blank=True, to='members.Profile')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='members.Site')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='meeting_files/')),
                ('title', models.CharField(max_length=128)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='meetings.Meeting')),
            ],
        ),
    ]
