# Generated by Django 2.2.2 on 2020-08-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='type',
            field=models.CharField(max_length=128),
        ),
    ]
