# Generated by Django 2.2 on 2021-12-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_auto_20211229_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='attendance_required',
            field=models.BooleanField(default=False),
        ),
    ]
