# Generated by Django 2.2.2 on 2020-08-13 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_auto_20200804_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='module',
            new_name='modules',
        ),
    ]
