# Generated by Django 2.2.2 on 2020-08-15 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_auto_20200813_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingfile',
            old_name='meeting',
            new_name='model',
        ),
    ]
