# Generated by Django 2.2.2 on 2020-08-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('meetings', '0005_auto_20200815_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='attendance_lists',
            new_name='lists_objects',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='module_objects',
            new_name='modules_objects',
        ),
        migrations.AddField(
            model_name='meeting',
            name='attendees_objects',
            field=models.ManyToManyField(blank=True, to='members.Profile'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='lists',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='attendees',
        ),
        migrations.AddField(
            model_name='meeting',
            name='attendees',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
