# Generated by Django 2.2.2 on 2020-09-28 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0008_meeting_modules_to_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='meetings', to='learning.Module'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='programming',
            field=models.ManyToManyField(blank=True, related_name='meetings', to='learning.Programming'),
        ),
    ]
