# Generated by Django 2.2.2 on 2020-08-04 16:56

import dashboard.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_for', models.TextField(blank=True, default='[]')),
                ('title', models.CharField(max_length=128)),
                ('length', models.CharField(blank=True, max_length=32)),
                ('description', models.TextField(blank=True)),
                ('facilitators', models.TextField(blank=True, default='[]')),
                ('links', models.TextField(blank=True, default='[]')),
                ('facilitators_objects', models.ManyToManyField(blank=True, related_name='facilitate_modules', to='members.Profile')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='members.Site')),
            ],
            bases=(dashboard.models.FileFieldMixin, dashboard.models.JsonM2MFieldModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Programming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('length', models.CharField(blank=True, max_length=32)),
                ('description', models.TextField(blank=True)),
                ('facilitators', models.TextField(blank=True, default='[]')),
                ('links', models.TextField(blank=True, default='[]')),
                ('facilitators_objects', models.ManyToManyField(blank=True, related_name='facilitate_programming', to='members.Profile')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programming', to='members.Site')),
            ],
            bases=(dashboard.models.FileFieldMixin, dashboard.models.JsonM2MFieldModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('required_for', models.TextField(blank=True, default='[]')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='members.Site')),
            ],
            bases=(dashboard.models.FileFieldMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProgrammingFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='learning_files/')),
                ('title', models.CharField(max_length=128)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='learning.Programming')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='members.Profile')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='learning.Theme')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='learning.Module')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='members.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='learning_files/')),
                ('title', models.CharField(max_length=128)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='learning.Module')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='learning.Theme'),
        ),
    ]
