# Generated by Django 2.2 on 2021-12-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulefile',
            name='file',
            field=models.FileField(upload_to='training_files/'),
        ),
        migrations.AlterField(
            model_name='programmingfile',
            name='file',
            field=models.FileField(upload_to='program_files/'),
        ),
    ]
