# Generated by Django 2.2.2 on 2020-08-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_auto_20200804_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programming',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
