#!/usr/bin/env bash

cd "${HOME}/circles"
git fetch --all
git reset --hard origin/master
python3 manage.py makemigrations --noinput
python3 manage.py migrate --noinput
exec python3 manage.py runserver
