# Generated by Django 2.2.2 on 2020-08-04 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circles_ID', models.CharField(blank=True, max_length=16, null=True)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=16, null=True)),
                ('race', models.CharField(blank=True, choices=[('White', 'White'), ('Black', 'Black'), ('Other', 'Other')], max_length=16, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('cell_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('other_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics')),
                ('e_relationship', models.CharField(blank=True, choices=[('Friend', 'Friend'), ('Parent', 'Parent'), ('Sibling', 'Sibling')], max_length=10, null=True)),
                ('e_first_name', models.CharField(blank=True, max_length=32, null=True)),
                ('e_last_name', models.CharField(blank=True, max_length=32, null=True)),
                ('e_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('status', models.CharField(blank=True, choices=[('Potential', 'Potential'), ('Active', 'Active'), ('Inactive', 'Inactive')], max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=32)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training', to='members.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=64)),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='members.Chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('Circle Leader', 'Circle Leader'), ('Ally', 'Ally'), ('Volunteer', 'Volunteer'), ('Resource Team', 'Resource Team'), ('Donor', 'Donor'), ('Other', 'Other')], max_length=64)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('cohort', models.CharField(blank=True, choices=[('CL', 'CL'), ('Ally', 'Ally')], max_length=32, null=True)),
                ('resource_team_name', models.CharField(blank=True, max_length=32, null=True)),
                ('resource_team_role', models.CharField(blank=True, max_length=32, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='members.Profile')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='members.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=64)),
                ('unit', models.CharField(blank=True, max_length=16)),
                ('city', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=32)),
                ('zip', models.CharField(max_length=16)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('ownership', models.CharField(blank=True, choices=[('N/A', 'N/A'), ('Rent', 'Rent'), ('Own', 'Own'), ('Doubled', 'Doubled')], default='N/A', max_length=16, null=True)),
                ('monthly_payment', models.CharField(blank=True, max_length=16, null=True)),
                ('habitat', models.CharField(blank=True, choices=[('N/A', 'N/A'), ('Yes', 'Yes'), ('No', 'No')], default='N/A', max_length=8, null=True)),
                ('safety', models.CharField(blank=True, choices=[('N/A', 'N/A'), ('Yes', 'Yes'), ('No', 'No')], default='N/A', max_length=8, null=True)),
                ('repair', models.CharField(blank=True, choices=[('N/A', 'N/A'), ('Yes', 'Yes'), ('No', 'No')], default='N/A', max_length=8, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residences', to='members.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='FilterSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=32, null=True)),
                ('filters', models.TextField(default='[]')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filtersets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChildInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_first_name', models.CharField(blank=True, max_length=16, null=True)),
                ('parent_last_name', models.CharField(blank=True, max_length=16, null=True)),
                ('parent_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('parent_street_address', models.CharField(blank=True, max_length=64, null=True)),
                ('parent_unit', models.CharField(blank=True, max_length=16, null=True)),
                ('parent_city', models.CharField(blank=True, max_length=32, null=True)),
                ('parent_state', models.CharField(blank=True, max_length=32, null=True)),
                ('parent_zip', models.CharField(blank=True, max_length=8, null=True)),
                ('e_relationship', models.CharField(blank=True, choices=[('Friend', 'Friend'), ('Parent', 'Parent'), ('Sibling', 'Sibling')], max_length=16, null=True)),
                ('e_first_name', models.CharField(blank=True, max_length=32, null=True)),
                ('e_last_name', models.CharField(blank=True, max_length=32, null=True)),
                ('e_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('physician_name', models.CharField(blank=True, max_length=32, null=True)),
                ('physician_practice', models.CharField(blank=True, max_length=64, null=True)),
                ('physician_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childinfos', to='members.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('middle_name', models.CharField(max_length=32)),
                ('relationship', models.CharField(blank=True, choices=[('Child', 'Child'), ('Grandchild', 'Grandchild'), ('Other Related', 'Other Related'), ('Other', 'Other')], max_length=16, null=True)),
                ('attendance', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=16, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=8, null=True)),
                ('known_health_issues', models.TextField(blank=True, null=True)),
                ('date_of_last_physical_exam', models.DateField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('medications', models.TextField(blank=True, null=True)),
                ('dietary_modifications', models.TextField(blank=True, null=True)),
                ('disabilities', models.TextField(blank=True, null=True)),
                ('child_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='members.ChildInfo')),
            ],
        ),
    ]
