# Generated by Django 2.2 on 2021-12-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='/profile_pics/default.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
