# Generated by Django 2.2.2 on 2019-07-17 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='firstname', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='lastname', max_length=20),
            preserve_default=False,
        ),
    ]
