# Generated by Django 2.2 on 2021-12-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20211229_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-Binary', 'Non-Binary')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='race',
            field=models.CharField(blank=True, choices=[('Asian American/Pacific Islander/Asian', 'Asian American/Pacific Islander/Asian'), ('Black/African American/African', 'Black/African American/African'), ('Hispanic/Latinx/Chicanx', 'Hispanic/Latinx/Chicanx'), ('Middle Eastern/Middle Eastern American', 'Middle Eastern/Middle Eastern American'), ('Native American/American Indian/Indigenous', 'Native American/American Indian/Indigenous'), ('Other', 'Other'), ('White/Caucasian/European', 'White/Caucasian/European')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='cohort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='position',
            field=models.CharField(choices=[('Ally', 'Ally'), ('Circle Leader', 'Circle Leader'), ('Donor', 'Donor'), ('Facilitator', 'Facilitator'), ('Resource Team', 'Resource Team'), ('Staff', 'Staff'), ('Volunteer', 'Volunteer'), ('Other', 'Other')], max_length=64),
        ),
    ]
