# Generated by Django 2.2.2 on 2019-07-19 00:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20190716_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='race',
            field=models.CharField(choices=[('White', 'White'), ('Black', 'Black'), ('Other', 'Other')], default='Other', max_length=10),
            preserve_default=False,
        ),
    ]
