# Generated by Django 2.2.2 on 2020-06-21 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_profile_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='position',
            field=models.CharField(choices=[('circle leader', 'Circle Leader'), ('ally', 'Ally'), ('volunteer', 'Volunteer'), ('resource team', 'Resource Team'), ('donor', 'Donor'), ('other', 'Other')], max_length=64),
        ),
    ]
