# Generated by Django 2.2.2 on 2019-07-19 00:33

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cell',
            field=phonenumber_field.modelfields.PhoneNumberField(default=0, max_length=128, region=None),
            preserve_default=False,
        ),
    ]
