# Generated by Django 2.2.2 on 2020-06-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20200622_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='relationship',
            field=models.CharField(blank=True, choices=[('Child', 'Child'), ('Grandchild', 'Grandchild'), ('Other Related', 'Other Related'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='childinfo',
            name='e_relationship',
            field=models.CharField(blank=True, choices=[('Friend', 'Friend'), ('Parent', 'Parent'), ('Sibling', 'Sibling')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='cohort',
            field=models.CharField(blank=True, choices=[('CL', 'CL'), ('Ally', 'Ally')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='position',
            field=models.CharField(choices=[('Circle Leader', 'Circle Leader'), ('Ally', 'Ally'), ('Volunteer', 'Volunteer'), ('Resource Team', 'Resource Team'), ('Donor', 'Donor'), ('Other', 'Other')], max_length=64),
        ),
    ]
