# Generated by Django 2.2.2 on 2019-07-19 00:37

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_profile_cell'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='other_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='race',
            field=models.CharField(choices=[('White', 'White'), ('Black', 'Black'), ('Other', 'Other')], max_length=10, null=True),
        ),
    ]
