# Generated by Django 2.2.2 on 2020-06-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20200622_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='subject',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
