# Generated by Django 2.2.2 on 2019-07-19 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20190718_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='zip',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
