# Generated by Django 2.2.2 on 2020-06-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20200622_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='e_relationship',
            field=models.CharField(blank=True, choices=[('Friend', 'Friend'), ('Parent', 'Parent'), ('Sibling', 'Sibling')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='race',
            field=models.CharField(blank=True, choices=[('White', 'White'), ('Black', 'Black'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('Potential', 'Potential'), ('Active', 'Active'), ('Inactive', 'Inactive')], max_length=16, null=True),
        ),
    ]
