# Generated by Django 2.2.2 on 2020-06-23 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20200622_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='members.Site'),
        ),
    ]
