# Generated by Django 2.2.2 on 2019-07-23 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_auto_20190722_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('street_address', models.CharField(max_length=64)),
                ('unit', models.CharField(blank=True, max_length=16)),
                ('city', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=32)),
                ('zip', models.CharField(max_length=5)),
                ('ownership', models.CharField(blank=True, choices=[('rent', 'Rent'), ('own', 'Own'), ('doubled', 'Doubled')], max_length=16, null=True)),
                ('habitat', models.BooleanField(blank=True, null=True)),
                ('safe', models.BooleanField(blank=True, null=True)),
                ('repair', models.BooleanField(blank=True, null=True)),
                ('payment', models.CharField(blank=True, max_length=8, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Profile')),
            ],
        ),
    ]
