# Generated by Django 2.2.2 on 2019-07-23 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_residence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
    ]
