# Generated by Django 2.2.2 on 2019-07-23 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_remove_profile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='end_date',
            field=models.DateField(blank=True),
        ),
    ]
