# Generated by Django 2.2.2 on 2019-07-23 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_auto_20190722_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
