# Generated by Django 2.2.2 on 2019-07-23 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_auto_20190722_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residences', to='members.Profile'),
        ),
    ]
