# Generated by Django 2.2.2 on 2019-07-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_auto_20190723_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
