# Generated by Django 2.2.2 on 2019-07-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_auto_20190725_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='habitat',
            field=models.CharField(blank=True, choices=[('n/a', 'N/A'), ('yes', 'Yes'), ('no', 'No')], max_length=8, null=True),
        ),
    ]
