# Generated by Django 2.2.2 on 2019-07-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_auto_20190726_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='habitat',
            field=models.CharField(choices=[('n/a', 'N/A'), ('yes', 'Yes'), ('no', 'No')], default='n/a', max_length=8),
        ),
        migrations.AlterField(
            model_name='residence',
            name='ownership',
            field=models.CharField(blank=True, choices=[('n/a', 'N/A'), ('rent', 'Rent'), ('own', 'Own'), ('doubled', 'Doubled')], default='n/a', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='residence',
            name='payment',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='residence',
            name='repair',
            field=models.CharField(choices=[('n/a', 'N/A'), ('yes', 'Yes'), ('no', 'No')], default='n/a', max_length=8),
        ),
        migrations.AlterField(
            model_name='residence',
            name='safe',
            field=models.CharField(choices=[('n/a', 'N/A'), ('yes', 'Yes'), ('no', 'No')], default='n/a', max_length=8),
        ),
    ]
