# Generated by Django 2.2.2 on 2019-07-26 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_auto_20190726_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='profile',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='residences', to='members.Profile'),
            preserve_default=False,
        ),
    ]
