# Generated by Django 2.2.2 on 2019-07-26 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_auto_20190726_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residences', to='members.Profile'),
        ),
    ]
