# Generated by Django 2.2.2 on 2019-07-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_auto_20190726_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='habitat',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Yes', 'Yes'), ('No', 'No')], default='N/A', max_length=8),
        ),
        migrations.AlterField(
            model_name='residence',
            name='ownership',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A'), ('Rent', 'Rent'), ('Own', 'Own'), ('Doubled', 'Doubled')], default='N/A', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='residence',
            name='repair',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Yes', 'Yes'), ('No', 'No')], default='N/A', max_length=8),
        ),
        migrations.AlterField(
            model_name='residence',
            name='safe',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Yes', 'Yes'), ('No', 'No')], default='N/A', max_length=8),
        ),
    ]
