# Generated by Django 2.2.2 on 2019-07-30 13:51

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='e_first_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='e_last_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='e_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='e_relationship',
            field=models.CharField(blank=True, choices=[('friend', 'Friend'), ('parent', 'Parent'), ('sibling', 'Sibling')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='race',
            field=models.CharField(blank=True, choices=[('white', 'White'), ('black', 'Black'), ('other', 'Other')], max_length=10, null=True),
        ),
    ]
