# Generated by Django 2.2.2 on 2019-07-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0024_auto_20190730_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('potential', 'Potential'), ('active', 'Active'), ('inactive', 'Inactive')], max_length=5, null=True),
        ),
    ]
