# Generated by Django 2.2.2 on 2019-07-30 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0025_profile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('position', models.CharField(choices=[('circle leader', 'Circle leader'), ('ally', 'Ally'), ('volunteer', 'Volunteer'), ('resource team', 'Resource team'), ('donor', 'Donor')], max_length=64)),
                ('cohort', models.CharField(blank=True, choices=[('leader', 'Leader'), ('ally', 'Ally')], max_length=6, null=True)),
                ('resource_team_name', models.CharField(blank=True, max_length=16, null=True)),
                ('resource_team_role', models.CharField(blank=True, max_length=16, null=True)),
                ('location', models.CharField(blank=True, max_length=16, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='members.Profile')),
            ],
        ),
    ]
