# Generated by Django 2.2.2 on 2019-08-01 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0026_auto_20190730_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('potential', 'Potential'), ('active', 'Active'), ('inactive', 'Inactive')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='cohort',
            field=models.CharField(blank=True, choices=[('cl', 'CL'), ('ally', 'Ally')], max_length=6, null=True),
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=32, null=True)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training', to='members.Profile')),
            ],
        ),
    ]
