# Generated by Django 2.2.2 on 2019-08-02 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0027_auto_20190801_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('relationship', models.CharField(blank=True, choices=[('child', 'Child'), ('grandchild', 'Grandchild'), ('other related', 'Other Related'), ('other', 'Other')], max_length=10, null=True)),
                ('attendance', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=10, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='members.Profile')),
            ],
        ),
    ]
