# Generated by Django 2.2.2 on 2019-08-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0028_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
