# Generated by Django 2.2.2 on 2019-08-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0029_child_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='health_issues',
            field=models.TextField(blank=True, null=True),
        ),
    ]
