# Generated by Django 2.2.2 on 2019-08-05 17:16

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0032_auto_20190805_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_first_name', models.CharField(blank=True, max_length=16, null=True)),
                ('parent_last_name', models.CharField(blank=True, max_length=16, null=True)),
                ('parent_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('parent_street_address', models.CharField(blank=True, max_length=64, null=True)),
                ('parent_unit', models.CharField(blank=True, max_length=16, null=True)),
                ('parent_city', models.CharField(blank=True, max_length=32, null=True)),
                ('parent_state', models.CharField(blank=True, max_length=32, null=True)),
                ('parent_zip', models.CharField(blank=True, max_length=5, null=True)),
                ('e_relationship', models.CharField(blank=True, choices=[('friend', 'Friend'), ('parent', 'Parent'), ('sibling', 'Sibling')], max_length=10, null=True)),
                ('e_first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('e_last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('e_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('physician_name', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('physician_practice', models.CharField(blank=True, max_length=64, null=True)),
                ('physician_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
            ],
        ),
        migrations.AlterField(
            model_name='child',
            name='first_name',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='child',
            name='last_name',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='child',
            name='middle_name',
            field=models.CharField(max_length=16),
        ),
    ]
