# Generated by Django 2.2.2 on 2019-08-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0033_auto_20190805_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childinfo',
            name='physician_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
