# Generated by Django 2.2.2 on 2019-08-05 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0034_auto_20190805_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='child_info',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='members.ChildInfo'),
            preserve_default=False,
        ),
    ]
