# Generated by Django 2.2.2 on 2019-08-13 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0036_auto_20190805_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childinfo',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childinfos', to='members.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='site',
            field=models.CharField(blank=True, default='Not Assigned', max_length=20, null=True),
        ),
    ]
