# Generated by Django 2.2.2 on 2019-08-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0037_auto_20190813_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='site',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
