# Generated by Django 2.2.2 on 2019-09-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0039_filterset'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterset',
            name='title',
            field=models.CharField(default='filterset', max_length=32),
            preserve_default=False,
        ),
    ]
