# Generated by Django 2.2.2 on 2019-12-27 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0040_filterset_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='zip',
        ),
    ]
