# Generated by Django 2.2.2 on 2019-12-30 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0041_auto_20191227_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='location',
            new_name='site',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='site',
        ),
    ]
