# Generated by Django 2.2.2 on 2019-12-30 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0042_auto_20191229_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='site',
            field=models.CharField(default='Not Available', max_length=16),
        ),
    ]
