# Generated by Django 2.2.2 on 2019-12-31 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0045_auto_20191231_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='site',
        ),
    ]
