# Generated by Django 2.2.2 on 2019-12-31 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0046_remove_role_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='site',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
