# Generated by Django 2.2.2 on 2019-12-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0047_role_site'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Site',
        ),
        migrations.AlterField(
            model_name='role',
            name='site',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
