# Generated by Django 2.2.2 on 2019-12-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0048_auto_20191231_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='role',
            name='site',
        ),
    ]
