# Generated by Django 2.2.2 on 2019-12-31 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0049_auto_20191231_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='members.Site'),
        ),
    ]
