# Generated by Django 2.2.2 on 2020-02-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0050_role_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='date_completed',
            new_name='end_date',
        ),
        migrations.AlterField(
            model_name='role',
            name='position',
            field=models.CharField(choices=[('circle leader', 'Circle Leader'), ('ally', 'Ally'), ('volunteer', 'Volunteer'), ('resource team', 'Resource Team'), ('donor', 'Donor')], max_length=64),
        ),
    ]
