# Generated by Django 2.2.2 on 2020-02-13 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0052_toolinputs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toolinputs',
            old_name='data',
            new_name='datatype',
        ),
    ]
