# Generated by Django 2.2.2 on 2020-02-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0053_auto_20200212_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolinputs',
            name='datatype',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
