# Generated by Django 2.2.2 on 2020-02-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0054_auto_20200213_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolinputs',
            name='datatype',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
