# Generated by Django 2.2.2 on 2020-02-14 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0055_auto_20200213_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolinputs',
            name='filterinput',
        ),
    ]
