# Generated by Django 2.2.2 on 2020-02-14 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0056_remove_toolinputs_filterinput'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toolinputs',
            old_name='filterby',
            new_name='filters',
        ),
    ]
