# Generated by Django 2.2.2 on 2020-02-14 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0058_auto_20200213_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolinputs',
            name='searchinput',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
