# Generated by Django 2.2.2 on 2020-02-23 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0059_auto_20200213_2310'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToolInputs',
        ),
    ]
